// Feather disable all

#macro BEADY_DEFAULT_MOVE_TO_DURATION  0.5
#macro BEADY_DEFAULT_MOVE_TO_CURVE     undefined

#macro BEADY_DEFAULT_ROTATE_TO_DURATION  0.5
#macro BEADY_DEFAULT_ROTATE_TO_CURVE     undefined

#macro BEADY_DEFAULT_ZOOM_TO_DURATION  0.5
#macro BEADY_DEFAULT_ZOOM_TO_CURVE     undefined

#macro BEADY_DEFAULT_KNOCKBACK_DURATION  0.3
#macro BEADY_DEFAULT_KNOCKBACK_CURVE     undefined

#macro BEADY_DEFAULT_SHAKE_DURATION  1.5
#macro BEADY_DEFAULT_SHAKE_CURVE     undefined

#macro BEADY_RANDOM_FUNCTION  random