// Feather disable all

#macro BEADY_BLOCK_NONE        0
#macro BEADY_BLOCK_MOVE        1
#macro BEADY_BLOCK_ZOOM        2
#macro BEADY_BLOCK_ANGLE       4
#macro BEADY_BLOCK_KNOCKBACK   8
#macro BEADY_BLOCK_SHAKE      16
#macro BEADY_BLOCK_ALL        (BEADY_BLOCK_MOVE | BEADY_BLOCK_ZOOM | BEADY_BLOCK_ANGLE | BEADY_BLOCK_KNOCKBACK | BEADY_BLOCK_SHAKE)